name = "UnitTestDesign"
uuid = "239896fa-e45a-40e8-9993-3c434b0bc450"
authors = ["Andrew Dolgert <adolgert@uw.edu>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Combinatorics = "1.0"
julia = "1.5"
